/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PengScriptEvent, PengScriptStatusName } from "./components/peng-script/peng-script";
export namespace Components {
    interface PengScript {
        /**
          * To expose error message for debugging etc:
         */
        "errorMessage": string;
        "isGlobal"?: boolean;
        "isIframe"?: boolean;
        "isOnce"?: boolean;
        "isReady"?: Function;
        "props"?: string | object;
        "showWhen"?: PengScriptStatusName;
        "srcProd": string;
        /**
          * To expose status message for debugging etc:
         */
        "statusMessage": PengScriptStatusName;
        "timeout"?: number;
        "trigger"?: 'now' | 'lazy' | 'click' | Function;
        "wait"?: number;
    }
}
declare global {
    interface HTMLPengScriptElement extends Components.PengScript, HTMLStencilElement {
    }
    var HTMLPengScriptElement: {
        prototype: HTMLPengScriptElement;
        new (): HTMLPengScriptElement;
    };
    interface HTMLElementTagNameMap {
        "peng-script": HTMLPengScriptElement;
    }
}
declare namespace LocalJSX {
    interface PengScript {
        /**
          * To expose error message for debugging etc:
         */
        "errorMessage"?: string;
        "isGlobal"?: boolean;
        "isIframe"?: boolean;
        "isOnce"?: boolean;
        "isReady"?: Function;
        "onPengscript"?: (event: CustomEvent<PengScriptEvent>) => void;
        "props"?: string | object;
        "showWhen"?: PengScriptStatusName;
        "srcProd"?: string;
        /**
          * To expose status message for debugging etc:
         */
        "statusMessage"?: PengScriptStatusName;
        "timeout"?: number;
        "trigger"?: 'now' | 'lazy' | 'click' | Function;
        "wait"?: number;
    }
    interface IntrinsicElements {
        "peng-script": PengScript;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "peng-script": LocalJSX.PengScript & JSXBase.HTMLAttributes<HTMLPengScriptElement>;
        }
    }
}
